<?php
/*
 * @ https://EasyToYou.eu - IonCube v11 Decoder Online
 * @ PHP 5.6
 * @ Decoder version: 1.0.4
 * @ Release: 02/06/2020
 *
 * @ ZendGuard Decoder PHP 5.6
 */

// Decoded file for php version 53.
echo "\n<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <title>Authorization</title>\n    <meta charset=\"utf-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n    <link href=\"libraries/bootstrap-icons.css\" rel=\"stylesheet\" type=\"text/css\"/>\n    <link href=\"libraries/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n   <script src=\"libraries/jquery-3.1.1.min.js\" type=\"text/javascript\"></script>\n   <link rel=\"icon\" type=\"image/png\" href=\"resources/favicon.png\">\n   <script src=\"application/mvc/views/custom_libraries/javascripts/jquery-confirm.min.js\"\n        type=\"text/javascript\"></script>\n    <link href=\"application/mvc/views/custom_libraries/css/jquery-confirm.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n  \n    ";
if ($cloudflare_enable_turnstile == 1) {
    echo " \n    <script src=\"https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback\" defer></script>\n    ";
}
echo "    \n    <style type=\"text/css\">\n      a {\n        text-decoration: none;\n    }\n    .login-page {\n        /*width: 100%;\n        height: 100vh;\n        display: inline-block;\n        display: flex;\n        align-items: center;*/\n    }\n    .form-right i {\n        font-size: 100px;\n    }\n    \n    .red_border{\n        border-color: red;\n    }\n  </style>  \n  \n  <script type=\"text/javascript\">\n\n        \$(document).ready(function () {\n            \$(\"#scodeform\").on('submit', (function (e) {\n                e.preventDefault();\n                \n                \n                \$(\"#submit_btn\").prop(\"disabled\",true);\n                \$.ajax({\n                    url: \"?r=login&f=authorize\",\n                    type: \"POST\",\n                    data: new FormData(this),\n                    contentType: false,\n                    cache: false,\n                    processData: false,\n                    dataType: 'json',\n                })\n                .done(function (data) {\n                    if(data.sc==1){\n                        window.location.href = data.url;\n                    }else{\n                        \$.alert({\n                            title: 'Alert!',\n                             content: 'Invalid code detected. A new code has been generated and sent to you.',\n                        });\n                        \$(\"#submit_btn\").prop(\"disabled\",false);\n                    }\n                })\n                .fail(function (jqXHR, textStatus, errorThrown) { \n                \n                });\n\n\n               \n            }));\n            \n            ";
if ($cloudflare_enable_turnstile == 1) {
    echo " \n            window.onloadTurnstileCallback = function () {\n                turnstile.render('#example-container', {\n                    sitekey: '0x4AAAAAAAaED9IwfuRgPp0K',\n                    callback: function(token) {\n                        \$(\"#submit_btn\").prop(\"disabled\",false);\n                    },\n                });\n            };\n            ";
}
echo "            \n        });\n        \n          \n     \n        \n\n        </script>\n \n</head>\n<body class=\"bg-light\">\n        <p style=\"position: absolute; left: 15px; bottom: 5px; font-family: sans-serif; font-size: 14px;\">";
echo $data["settings"]["upsilon_contact_info"];
echo "</p>\n    <div class=\"login-page \">\n        <div class=\"container\">\n            \n            <div class=\"row \">\n                <div class=\"col-lg-6 offset-lg-3\" style=\"text-align: center\">\n                    <img src=\"upsilon-logo-n.png\" />\n                </div>\n            </div>\n            <div class=\"row\">\n                <div class=\"col-lg-6 offset-lg-3\">\n                    <div class=\"bg-white shadow rounded\">\n                        <div class=\"row\">\n                            \n                            <div class=\"col-md-12 pe-0\">\n                                <div class=\"form-left h-100 py-4 px-5\">\n                                    <form id=\"scodeform\" class=\"row g-4\" role=\"form\" method=\"post\" enctype=\"multipart/form-data\">\n                                            <div class=\"col-12 mt-3\">\n                                                <label>Code<span class=\"text-danger\">*</span></label>\n                                                <div class=\"input-group\">\n                                                    <div class=\"input-group-text\"><i class=\"bi bi-person-fill\"></i></div>\n                                                    <input name=\"scode\" id=\"scode\" type=\"text\" class=\"form-control\" placeholder=\"Enter Authorization Code Here\" autocomplete=\"off\">\n                                                </div>\n                                            </div>\n\n                                     \n                                        \n                                            ";
if ($cloudflare_enable_turnstile == 1) {
    echo "                                            <div class=\"col-lg-8 col-md-8 col-sm-12 col-xs-12  mt-2\">\n                                                <div class=\"input-group\" style=\"display: inline;\">\n                                                    <div id=\"example-container\" style=\"margin-top: 10px;\"></div>\n                                                </div>\n                                            </div>\n                                        \n                                             <div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12  mt-2\">\n                                              <button disabled=\"\" id=\"submit_btn\" type=\"submit\" class=\"btn btn-primary px-4 float-end mt-2\" style=\"height: 63px;\">Authorize This Device</button>\n                                            </div>\n                                        \n                                        <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12  mt-5\" style=\"text-align: center; font-size: 12px;\" >\n                                                <a  href=\"?\"  class=\" px-0 mt-2\" >Back to login page</a>\n                                            </div>\n                                        \n                                       \n                                        \n                                        \n                                           ";
} else {
    echo " \n                                            \n                                        \n                                        \n                                        <div class=\"col-12  mt-2\">\n                                            <button  id=\"submit_btn\" type=\"submit\" class=\"btn btn-primary px-4 float-end mt-2\">Authorize This Device</button>\n                                            </div>\n                                        \n                                        <div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12  mt-5\" style=\"text-align: center; font-size: 12px;\" >\n                                                <a  href=\"?\"  class=\" px-0 mt-2\" >Back to login page</a>\n                                            </div>\n                                        ";
}
echo "                                        \n                                        \n                                            \n                                    </form>\n                                </div>\n                            </div>\n                            \n                        </div>\n                    </div>\n                    <p class=\"text-end text-secondary mt-3\">&copy; 2017 <b>UPSILON</b></p>\n                </div>\n            </div>\n        </div>\n    </div>\n\n    <!-- Bootstrap JS -->\n     \n</body>\n</html>";

?>