<?php
/*
 * @ https://EasyToYou.eu - IonCube v11 Decoder Online
 * @ PHP 5.6
 * @ Decoder version: 1.0.4
 * @ Release: 02/06/2020
 *
 * @ ZendGuard Decoder PHP 5.6
 */

// Decoded file for php version 53.
echo "<!DOCTYPE html>\r\n<!--\r\nTo change this license header, choose License Headers in Project Properties.\r\nTo change this template file, choose Tools | Templates\r\nand open the template in the editor.\r\n-->\r\n<html>\r\n    <head>\r\n        <title>All Cashboxes</title>\r\n        <meta charset=\"UTF-8\">\r\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n        <link rel=\"icon\" type=\"image/png\" href=\"resources/favicon.png\">\r\n        \r\n        <script src=\"libraries/jquery-3.1.1.min.js\" type=\"text/javascript\"></script>\r\n\r\n        <script src=\"libraries/bootstrap-3.3.7-dist/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n        <link href=\"libraries/bootstrap-3.3.7-dist/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n        \r\n        <script src=\"libraries/bootstrap-plugins/DataTables-1.10.13/media/js/jquery.dataTables.min.js\" type=\"text/javascript\"></script>\r\n        <script src=\"libraries/bootstrap-plugins/DataTables-1.10.13/media/js/dataTables.bootstrap.min.js\" type=\"text/javascript\"></script>\r\n        <link href=\"libraries/bootstrap-plugins/DataTables-1.10.13/media/css/dataTables.bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n\r\n        \r\n        <link href=\"application/mvc/views/custom_libraries/css/global.css?rnd=";
echo self::generateRandomStringComplex();
echo "\" rel=\"stylesheet\" type=\"text/css\"/>\r\n                \r\n        <link href=\"application/mvc/views/custom_libraries/css/dashboard.css?rnd=";
echo self::generateRandomStringComplex();
echo "\" rel=\"stylesheet\" type=\"text/css\"/>\r\n        <script src=\"application/mvc/views/custom_libraries/javascripts/global.js?rnd=";
echo self::generateRandomStringComplex();
echo "\" type=\"text/javascript\"></script>\r\n        <script src=\"application/mvc/views/custom_libraries/javascripts/collect_quantities.js?rnd=";
echo self::generateRandomStringComplex();
echo "\" type=\"text/javascript\"></script>\r\n        <script src=\"libraries/bootstrap-plugins/bootstrap-select-master/bootstrap-select-master/dist/js/bootstrap-select.min.js\" type=\"text/javascript\"></script>\r\n        <link href=\"libraries/bootstrap-plugins/bootstrap-select-master/bootstrap-select-master/dist/css/bootstrap-select.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n        \r\n        <link href=\"libraries/morris.js-0.5.1/morris.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n        <script src=\"libraries/morris.js-0.5.1/morris.min.js\" type=\"text/javascript\"></script>\r\n        <script src=\"libraries/raphael-min.js\" type=\"text/javascript\"></script>\r\n        <script src=\"libraries/notify.min.js\" type=\"text/javascript\"></script>\r\n        <link href=\"application/mvc/views/custom_libraries/svgs/font/style.css?rnd=";
echo self::generateRandomStringComplex();
echo "\" rel=\"stylesheet\" type=\"text/css\"/>\r\n        \r\n        <link href=\"libraries/bootstrap-plugins/bootstrap-sweetalert-master/dist/sweetalert.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n        <script src=\"libraries/bootstrap-plugins/bootstrap-sweetalert-master/dist/sweetalert.min.js\" type=\"text/javascript\"></script>\r\n        \r\n        <script src=\"libraries/cleave.js-master/dist/cleave.min.js\" type=\"text/javascript\"></script>\r\n        \r\n        <script type=\"text/javascript\">\r\n            \r\n            \$(document).ready(function () {\r\n                refresh_cashboxes();\r\n            });\r\n            \r\n            function refresh_cashboxes(){\r\n                var _data=[];\r\n                \$.getJSON(\"?r=cashboxes&f=get_all_cashboxes\", function (data) {\r\n                    _data=data;\r\n                }).done(function () {\r\n                    \$(\"#cashboxes_container\").empty();\r\n                    for(var i=0;i<_data.stores.length;i++){\r\n                        \$(\"#cashboxes_container\").append('<div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\\n\\\r\n                            <div class=\"panel panel-primary\">\\n\\\r\n                                <div class=\"panel-heading\">'+_data.stores[i].name+'</div>\\n\\\r\n                                <div class=\"panel-body\">\\n\\\r\n                                    <b>Amount LBP:</b> '+_data.stores[i].net_lbp+' LBP<br/>\\n\\\r\n                                    <b>Amount USD:</b> '+_data.stores[i].net_usd+' USD\\n\\\r\n                                </div>\\n\\\r\n                            </div>\\n\\\r\n                        </div>');\r\n                    }\r\n                });\r\n            }\r\n            \r\n        </script>\r\n    </head>\r\n    <body >\r\n        \r\n        ";
include "application/mvc/views/topMenu.php";
echo "\r\n        <div class=\"container-fluid\" id=\"main\">\r\n            <div class=\"row\">\r\n                <div class=\"col-lg-12\">\r\n                    <h3>All Opened Cashboxes</h3>\r\n                </div>\r\n                \r\n            </div>\r\n            <div class=\"row\" style=\"margin-top: 0px;\" id=\"cashboxes_container\">\r\n            </div> \r\n        </div>\r\n        \r\n        <div class=\"sk-circle-layer\">\r\n            <div class=\"sk-circle\">\r\n                <div class=\"sk-circle1 sk-child\"></div>\r\n                <div class=\"sk-circle2 sk-child\"></div>\r\n                <div class=\"sk-circle3 sk-child\"></div>\r\n                <div class=\"sk-circle4 sk-child\"></div>\r\n                <div class=\"sk-circle5 sk-child\"></div>\r\n                <div class=\"sk-circle6 sk-child\"></div>\r\n                <div class=\"sk-circle7 sk-child\"></div>\r\n                <div class=\"sk-circle8 sk-child\"></div>\r\n                <div class=\"sk-circle9 sk-child\"></div>\r\n                <div class=\"sk-circle10 sk-child\"></div>\r\n                <div class=\"sk-circle11 sk-child\"></div>\r\n                <div class=\"sk-circle12 sk-child\"></div>\r\n            </div>\r\n        </div>\r\n    </body>\r\n</html>\r\n\r\n";

?>